var plato_1   = new Vue({el: '#plato_1', data: {message: 'Arroz Atollado'}})
var plato_2   = new Vue({el: '#plato_2', data: {message: 'Arroz con Camarones'}})
var plato_3   = new Vue({el: '#plato_3', data: {message: 'Arroz con Carnes'}})
var plato_4   = new Vue({el: '#plato_4', data: {message: 'Arroz Paisa'}})
var plato_5   = new Vue({el: '#plato_5', data: {message: 'Arroz con Pollo'}})
var plato_6   = new Vue({el: '#plato_6', data: {message: 'Bagre en Salsa'}})
var plato_7   = new Vue({el: '#plato_7', data: {message: 'Chuleta Valluna'}})
var plato_8   = new Vue({el: '#plato_8', data: {message: 'Corrientazo Típico'}})
var plato_9   = new Vue({el: '#plato_9', data: {message: 'Poteca de Ahuyama'}})
var plato_10  = new Vue({el: '#plato_10', data: {message: 'Sancocho Trifásico'}})
var plato_11  = new Vue({el: '#plato_11', data: {message: 'Sobrebarriga al Horno'}})
var plato_12  = new Vue({el: '#plato_12', data: {message: 'Sopa de Arroz'}})
var plato_13  = new Vue({el: '#plato_13', data: {message: 'Arroz con Camarones'}})
var plato_14  = new Vue({el: '#plato_14', data: {message: 'Bagre en Salsa'}})
var plato_15  = new Vue({el: '#plato_15', data: {message: 'Chuleta Valluna'}})

var fecha = new Date().getDate()

var fecha_Lunes = new Vue({el: '#fecha_Lunes', data:{message: fecha+4+ ' de octubre'}})
var fecha_Martes = new Vue({el: '#fecha_Martes', data:{message: fecha+5+ ' de octubre'}})
var fecha_Miercoles = new Vue({el: '#fecha_Miercoles', data:{message: fecha+6+ ' de octubre'}})
var fecha_Jueves = new Vue({el: '#fecha_Jueves', data:{message: fecha+7+ ' de octubre'}})
var fecha_Viernes = new Vue({el: '#fecha_Viernes', data:{message: fecha+8+ ' de octubre'}})

